services:
  web1:
    container_name: web1
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    networks:
      - some-net
    healthcheck:
      interval: 5s
      retries: 3
      test: curl http://localhost:8080/metrics
  web2:
    container_name: web2
    build: .
    ports:
      - "8081:8080"
    environment:
      PORT: 8080
    networks:
      - some-net
    healthcheck:
      interval: 5s
      retries: 3
      test: curl http://localhost:8080/metrics
  web3:
    container_name: web3
    build: .
    ports:
      - "8082:8080"
    environment:
      PORT: 8080
    networks:
      - some-net
    healthcheck:
      interval: 5s
      retries: 3
      test: curl http://localhost:8080/metrics

  prometheus:
    container_name: prometheus-server
    image: "prom/prometheus:latest"
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - prometheus:/etc/prometheus
    networks:
      - some-net
    depends_on:
      web1:
        condition: service_healthy
      web2:
        condition: service_healthy
      web3:
        condition: service_healthy
volumes:
  prometheus:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus
networks:
  some-net:
    driver: bridge

